version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: twitter_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
